displayName: Error Pages
type: middleware

import: github.com/3-w-c/traefik-error-page

summary: 'Like the error middleware but with a twist'

testData:
  status: ['400-499', '500-599']
  service: 'https://http.cat'
  query: '/{status}'
  contentsOnly: true
  contentsOnlyMatch: ""
  debug: false
